/**
 * @brief Zenith gains header
 * @author Autogenerated by HeaderGen
 * @author Bertrand Bevillard <bertrand@zenithaero.com>
 */

namespace ZenithGains {
	static struct {
		float scalingSpeed = 15;
	} constants;

	static struct {
		float enable = 1;
		float FF = -1.8021;
		float Omega = 0.9684;
		float Kp = 0.58646;
		float Kd = 0;
		float Ki = 0.001113;
		float mat[2][3] = {{.1f, .2f, .5f}, {.2f, .3f, .4f}};
	} pitch;

	static struct {
		float enable = 1;
		float FF = 0;
		float Omega = 0.85052;
		float Kp = 1.1597;
		float Kd = 0.006842;
		float Ki = 0;
	} roll;

	static struct {
		float enable = 1;
		float FF = 0;
		float Kd = 0;
		float Kcoord = 0;
		float Ki = 0;
		float Kslip = 0;
	} yaw;

	static struct {
		float enable = 1;
		float pitchFF = 0.054431;
		float rollFF = 10;
		float thrCruise = 0.12727;
		float hDotMax = 5;
		float hDotMin = 5;
		float thrMax = 1;
		float thrMin = 0;
		float wc = 12.5664;
		float Wspe = 1;
		float Wske = 1;
		float skeFF = 0;
		float TcInv = 0.37172;
		float Ki = 0.099;
		float totKd = 0.009;
		float balKd = 0.009;
	} tecs;

	static struct {
		float enable = 1;
		float rollFF = 0;
		float distOverPeriodMin = 1;
		float damping = 0.8;
		float periodInv = 0.054435;
		float xTrackI = 0;
	} L1;

	static struct {
		float h = 40;
		float hDot = 0;
		float tas = 12.9987;
		float tasDot = 0;
		float xTrack = 0;
		float yTrack = 0;
		float psiTrackDeg = 0;
	} cmd;

};
