
// Autogenerated by CodeGen.py
#pragma once


#ifdef MODEL
# error MODEL already defined
#endif
#define MODEL Z1_Sim

#ifdef NUMST
# error NUMST already defined
#endif
#define NUMST 3

#ifdef NCSTATES
# error NCSTATES already defined
#endif
#define NCSTATES 33

#ifdef HAVESTDIO
# error HAVESTDIO already defined
#endif
#define HAVESTDIO

#ifdef RT
# error RT already defined
#endif
#define RT

#ifdef USE_RTMODEL
# error USE_RTMODEL already defined
#endif
#define USE_RTMODEL

#ifdef UNIX
# error UNIX already defined
#endif
#define UNIX

#ifdef CLASSIC_INTERFACE
# error CLASSIC_INTERFACE already defined
#endif
#define CLASSIC_INTERFACE 0

#ifdef ALLOCATIONFCN
# error ALLOCATIONFCN already defined
#endif
#define ALLOCATIONFCN 0

#ifdef TID01EQ
# error TID01EQ already defined
#endif
#define TID01EQ 1

#ifdef MAT_FILE
# error MAT_FILE already defined
#endif
#define MAT_FILE 0

#ifdef ONESTEPFCN
# error ONESTEPFCN already defined
#endif
#define ONESTEPFCN 1

#ifdef TERMFCN
# error TERMFCN already defined
#endif
#define TERMFCN 1

#ifdef MULTI_INSTANCE_CODE
# error MULTI_INSTANCE_CODE already defined
#endif
#define MULTI_INSTANCE_CODE 1

#ifdef INTEGER_CODE
# error INTEGER_CODE already defined
#endif
#define INTEGER_CODE 0

#ifdef MT
# error MT already defined
#endif
#define MT 0
