/**
 * @brief xuav gain header
 * @author Autogenerated by HeaderGen
 * @date 27-Aug-2020 09:49:15
 * @hash 55a5057064031261be54d664b9c25b0d
 */

namespace xuav_controllerData {
	static struct {
		const double scalingSpeed = 12.000000;
	} constants;

	static struct {
		const double enable = 1.000000;
		const double FF = -0.872320;
		const double maxCmdDeg = 30.000000;
		const double maxErrDeg = 30.000000;
		const double maxElevDeg = 15.000000;
		const char *stateNames[4] = {"thetaErrDeg", "thetaErrInt", "<qDeg>", "<hDot>"};
		const double K[1][4] = {{-0.091900, -0.193100, 0.124200, 1.123400}};
	} pitch;

	static struct {
		const double enable = 1.000000;
		const double ailFF = 0.000400;
		const double rudFF = 0.002170;
		const double maxCmdDeg = 30.000000;
		const double maxErrDeg = 30.000000;
		const double maxAilDeg = 25.000000;
		const double maxRudDeg = 15.000000;
		const char *stateNames[4] = {"phiErrDeg", "phiErrInt", "<pDeg>", "rDegHP"};
		const double K[2][4] = {{0.249000, -0.010300, -0.044700, -0.005300}, {0.227200, -0.208900, -0.309900, 0.298200}};
	} rollYaw;

	static struct {
		const double enable = 1.000000;
		const double thrFF = 0.119960;
		const double pitchFF = -1.368796;
		const double maxAltErr = 5.000000;
		const double maxTasErr = 5.000000;
		const double maxSpdCmd = 20.000000;
		const double maxThr = 1.000000;
		const char *stateNames[7] = {"hErr", "hErrInt", "tasErr", "tasErrInt", "hDotErr", "<thetaDeg>", "<qDeg>"};
		const double K[2][7] = {{-0.270800, -0.002600, 0.236500, 0.012200, -0.136300, 0.076100, 0.011500}, {16.921200, 0.144600, -11.104800, -0.675800, 9.809400, -3.086500, -0.746700}};
	} spdalt;

	static struct {
		const double enable = 0.000000;
		const double rollFF = 0.000000;
		const double L1 = 80.000000;
	} xTrack;

};
