/**
 * @brief xuav gain header
 * @author Autogenerated by HeaderGen
 * @date 22-Aug-2020 20:20:29
 * @hash 700efe24e55c89a0497e598cfd2eab08
 */

namespace xuav_controllerData {
	static struct {
		const double scalingSpeed = 12.000000;
	} constants;

	static struct {
		const double enable = 1.000000;
		const double FF = -2.378180;
		const double maxCmdDeg = 30.000000;
		const double maxErrDeg = 30.000000;
		const double maxElevDeg = 30.000000;
		const char *stateNames[4] = {"thetaErrDeg", "thetaErrInt", "<qDeg>", "<hDot>"};
		const double K[1][4] = {{0.100200, 0.557900, -0.147400, -2.651400}};
	} pitch;

	static struct {
		const double enable = 1.000000;
		const double ailFF = -0.000540;
		const double rudFF = -0.001560;
		const double maxCmdDeg = 30.000000;
		const double maxErrDeg = 30.000000;
		const double maxAilDeg = 30.000000;
		const double maxRudDeg = 30.000000;
		const char *stateNames[4] = {"phiErrDeg", "phiErrInt", "<pDeg>", "<rDeg>"};
		const double K[2][4] = {{0.159000, -0.018400, -0.122600, 0.100000}, {-0.274900, -0.196000, -0.378800, 0.609000}};
	} rollYaw;

	static struct {
		const double enable = 1.000000;
		const double thrFF = 0.024360;
		const double pitchFF = 1.088620;
		const double maxAltErr = 5.000000;
		const double maxTasErr = 5.000000;
		const double maxSpdCmd = 20.000000;
		const double maxThr = 1.000000;
		const char *stateNames[7] = {"hErr", "hErrInt", "tasErr", "tasErrInt", "hDotErr", "<thetaDeg>", "<qDeg>"};
		const double K[2][7] = {{0.003500, 0.001500, 0.026800, 0.038300, 0.255400, 0.067100, -0.005900}, {8.141400, -0.019000, -1.209400, -0.494300, 12.884400, 0.188700, -0.757000}};
	} spdalt;

	static struct {
		const double enable = 1.000000;
		const double rollFF = 0.000000;
		const double L1 = 80.000000;
	} xTrack;

};
