/**
 * @brief xuav gain header
 * @author Autogenerated by HeaderGen
 * @date 19-Oct-2020 11:50:21
 * @hash b27eeb6324e9730d1dc79267c94d6a89
 */

namespace xuav_controllerData {
	static struct {
		const float scalingSpeed = 12.000000;
	} constants;

	static struct {
		const float enable = 1.000000;
		const float maxCmdDeg = 30.000000;
		const float maxElevDeg = 25.000000;
		const float maxIntCmdDeg = 10.000000;
		const char *stateNames[3] = {"thetaErrDeg", "thetaErrInt", "<qDeg>"};
		const float Ktas[2] = {12.000000, 20.000000};
		const float K[6] = {0.247800, 0.247800, 0.091500, 0.091500, -0.063500, -0.063500};
	} pitch;

	static struct {
		const float enable = 1.000000;
		const float maxCmdDeg = 30.000000;
		const float maxAilDeg = 25.000000;
		const float maxRudDeg = 25.000000;
		const float maxIntCmdDeg = 10.000000;
		const char *stateNames[4] = {"phiErrDeg", "phiErrInt", "<pDeg>", "rDegHP"};
		const float Ktas[2] = {12.000000, 20.000000};
		const float K[16] = {0.540200, 0.540200, 0.046700, 0.046700, -0.149900, -0.149900, -0.057700, -0.057700, 0.000000, 0.000000, 0.000000, 0.000000, 0.067100, 0.067100, -0.426900, -0.426900};
	} rollYaw;

	static struct {
		const float enable = 1.000000;
		const float maxAltErr = 5.000000;
		const float maxTasErr = 5.000000;
		const float maxSpdCmd = 20.000000;
		const float maxThr = 1.000000;
		const float maxIntThrCmd = 0.300000;
		const float maxIntThetaCmdDeg = 8.000000;
		const char *stateNames[7] = {"hErr", "hErrInt", "tasErr", "tasErrInt", "hDotErr", "<thetaDeg>", "<qDeg>"};
		const float Ktas[2] = {12.000000, 20.000000};
		const float K[28] = {0.000000, 0.000000, 0.001200, 0.001200, 0.165100, 0.165100, 0.012900, 0.012900, 0.074600, 0.074600, 0.037100, 0.037100, -0.000600, -0.000600, 6.634300, 6.634300, 0.017500, 0.017500, -0.000000, -0.000000, -0.074800, -0.074800, 5.937500, 5.937500, -0.760400, -0.760400, -0.013200, -0.013200};
	} spdAlt;

	static struct {
		const float enable = 1.000000;
		const float L1 = 80.000000;
		const float legacyDamping = 0.850000;
		const float legacyPeriodInv = 0.040000;
		const float legacyI = 0.000000;
	} xTrack;

	static struct {
		const float tas[6] = {10.000000, 12.000000, 14.000000, 16.000000, 18.000000, 20.000000};
		const float ux[6] = {9.982900, 11.999150, 13.997930, 15.989410, 17.977820, 19.964990};
		const float uy[6] = {-0.000050, -0.000000, -0.000010, -0.000070, -0.000190, -0.000360};
		const float uz[6] = {0.584500, 0.143130, -0.240640, -0.582060, -0.893400, -1.182890};
		const float phi[6] = {-0.000090, -0.000020, 0.000040, 0.000120, 0.000210, 0.000300};
		const float theta[6] = {0.058480, 0.011930, -0.017190, -0.036390, -0.049650, -0.059180};
		const float psi[6] = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		const float thr[6] = {0.142520, 0.129640, 0.156670, 0.173340, 0.214760, 0.246360};
		const float ailDeg[6] = {-0.004730, -0.000920, 0.001170, 0.002490, 0.003390, 0.003970};
		const float elevDeg[6] = {3.915700, 3.000950, 2.500960, 2.194050, 1.995470, 1.857560};
		const float rudDeg[6] = {-0.037340, -0.007620, 0.009270, 0.019800, 0.027210, 0.031690};
	} trim;

};
