/**
 * @brief Z1f gain header
 * @author Autogenerated by HeaderGen
 * @date 10-Sep-2020 16:32:41
 * @hash 5fd71e69751081ccf8a80001a4a0dce8
 */

namespace Z1f_controllerData {
	static struct {
		const float scalingSpeed = 15.000000;
	} constants;

	static struct {
		const float enable = 1.000000;
		const float FF = -1.366230;
		const float maxCmdDeg = 30.000000;
		const float maxElevDeg = 15.000000;
		const char *stateNames[3] = {"thetaErrDeg", "thetaErrInt", "<qDeg>"};
		const float K[1][3] = {{0.513500, 0.152100, -0.185300}};
		const float maxErrI = 98.619329;
	} pitch;

	static struct {
		const float enable = 1.000000;
		const float ailFF = 0.000000;
		const float rudFF = -0.000000;
		const float maxCmdDeg = 30.000000;
		const float maxAilDeg = 25.000000;
		const float maxRudDeg = 15.000000;
		const char *stateNames[4] = {"phiErrDeg", "phiErrInt", "<pDeg>", "rDegHP"};
		const float K[2][4] = {{0.702100, 0.047600, -0.603300, 0.175400}, {0.000000, 0.000000, 1.350200, -1.145900}};
		const float maxErrI = 525.210084;
	} rollYaw;

	static struct {
		const float enable = 1.000000;
		const float thrFF = 0.006120;
		const float pitchFF = -1.530370;
		const float maxAltErr = 3.000000;
		const float maxTasErr = 3.000000;
		const float maxSpdCmd = 20.000000;
		const float maxThr = 1.000000;
		const char *stateNames[7] = {"hErr", "hErrInt", "tasErr", "tasErrInt", "hDotErr", "<thetaDeg>", "<qDeg>"};
		const float K[2][7] = {{0.089400, 0.000000, 0.121200, 0.000000, 0.142500, 0.025700, -0.036300}, {5.262100, 0.051500, -1.249400, -0.379900, 7.030500, -1.179700, -0.176300}};
		const float maxAltErrI = 582.524272;
		const float maxTasErrI = 78.968150;
	} spdAlt;

	static struct {
		const float enable = 1.000000;
		const float rollFF = 0.000000;
		const float L1 = 120.000000;
		const float legacyDamping = 0.850000;
		const float legacyPeriodInv = 0.025000;
		const float legacyI = 0.000000;
	} xTrack;

};
