/**
 * @brief Zenith gains file
 * @author Autogenerated by exportGains
 * @author Bertrand Bevillard <bertrand@zenithaero.com>
 */

namespace ZenithGains {
	static struct {
		float enable = 0;
		float FF = -3.612;
		float Omega = 1.9734;
		float Kp = 0.11102;
		float Kd = 0.019745;
		float Ki = 0.24062;
	} pitch;

	static struct {
		float enable = 1;
		float FF = -0.000107;
		float Omega = 1;
		float Kp = 0.21941;
		float Kd = 0.065625;
		float Ki = 5.7e-05;
	} roll;

	static struct {
		float enable = 1;
		float FF = -0.00107;
		float Kd = 0;
		float Kcoord = 0;
		float Ki = 0;
		float Kslip = 0;
	} yaw;

	static struct {
		float enable = 0;
		float pitchFF = 1.0485;
		float thrFF = 0.056;
		float rollFF = 10;
		float thrCruise = 0;
		float hDotMax = 5;
		float hDotMin = -2;
		float thrMax = 1;
		float thrMin = 0;
		float wc = 12.5664;
		float Wspe = 1;
		float Wske = 1;
		float skeFF = 0;
		float TcInv = 0.5;
		float Ki = 0.199;
		float totKd = 0.009;
		float balKd = 2.3054;
	} tecs;

	static struct {
		float enable = 1;
		float distOverPeriodMin = 1;
		float damping = 0.9;
		float periodInv = 0.047728;
		float xTrackI = 0;
	} L1;

};
