/**
 * @brief Zenith gains header
 * @author Autogenerated by HeaderGen
 * @author Bertrand Bevillard <bertrand@zenithaero.com>
 */

namespace ZenithGains {
	static struct {
		float scalingSpeed = 15;
	} constants;

	static struct {
		float enable = 1;
		float FF = -2.3644;
		float Omega = 0.79705;
		float Kp = 0.081891;
		float Kd = 0.078729;
		float Ki = 0.27408;
	} pitch;

	static struct {
		float enable = 1;
		float FF = 0;
		float Omega = 1;
		float Kp = 0.064811;
		float Kd = 0.10516;
		float Ki = 0.86795;
	} roll;

	static struct {
		float enable = 1;
		float FF = 0;
		float Kd = 0;
		float Kcoord = 0;
		float Ki = 0;
		float Kslip = 0;
	} yaw;

	static struct {
		float enable = 1;
		float pitchFF = 1.06;
		float rollFF = 10;
		float thrCruise = 0.06621;
		float hDotMax = 5;
		float hDotMin = 5;
		float thrMax = 1;
		float thrMin = 0;
		float wc = 12.5664;
		float Wspe = 1;
		float Wske = 1;
		float skeFF = 0;
		float TcInv = 1.2243;
		float Ki = 0.099;
		float totKd = 0.75887;
		float balKd = 2.6696;
	} tecs;

	static struct {
		float enable = 1;
		float rollFF = 0;
		float distOverPeriodMin = 1;
		float damping = 0.8;
		float periodInv = 0.05593;
		float xTrackI = 0;
	} L1;

	static struct {
		float h = 22.1;
		float hDot = 0;
		float tas = 11.9943;
		float tasDot = 0;
		float xTrack = 0;
		float yTrack = 1;
		float psiTrackDeg = 0;
	} cmd;

};
