/**
 * @brief xuav config header
 * @author Autogenerated by HeaderGen
 * @date 10-Sep-2020 16:49:57
 * @hash 05832a9e569101fefe97bce4db887ae9
 */


namespace xuav_config {
	static const float M = 2.740000;
	static const float I[3][3] = {{0.176700, 0.000000, -0.008740}, {0.000000, 0.126300, 0.000000}, {-0.008740, 0.000000, 0.296300}};
	static const float S = 0.512970;
	static const float b = 1.880000;
	static const float c = 0.282440;
	static const float CG[1][3] = {{0.000000, 0.000000, 0.000000}};
	static const float CP[1][3] = {{0.000000, 0.000000, 0.000000}};
	static const float thrustStatic = 2.670000;
	static const float thrustGain = 0.003400;
	static const float servoMap[3][5] = {{1.000000, 0.000000, 0.000000, 0.000000, 0.000000}, {0.000000, 1.000000, 0.000000, 0.000000, 0.000000}, {0.000000, 0.000000, 1.000000, 0.000000, 0.000000}};
	static const float servoMaxDeg[1][3] = {{25.000000, 15.000000, 15.000000}};
	static const float motorMap[2][2] = {{1.000000, 0.000000}, {0.000000, 1.000000}};
	static const float motorMax[1][2] = {{1.000000, 1.000000}};
};
