/**
 * @brief xuav config header
 * @author Autogenerated by HeaderGen
 * @date 25-Aug-2020 16:44:50
 * @hash e0ce5ee2f888698bb47f016f1f97304f
 */


namespace xuav_config {
	static const double M = 2.740000;
	static const double I[3][3] = {{0.176700, 0.000000, -0.008740}, {0.000000, 0.126300, 0.000000}, {-0.008740, 0.000000, 0.296300}};
	static const double S = 0.512970;
	static const double b = 1.880000;
	static const double c = 0.282440;
	static const double CG[1][3] = {{0.000000, 0.000000, 0.000000}};
	static const double CP[1][3] = {{0.000000, 0.000000, 0.000000}};
};
