/**
 * @brief Z1f config header
 * @author Autogenerated by HeaderGen
 * @date 10-Sep-2020 16:49:53
 * @hash 00f9726665dc44452e0c9b8129db2269
 */


namespace Z1f_config {
	static const float M = 31.300000;
	static const float I[3][3] = {{126.700000, 0.050750, -0.843700}, {0.050750, 9.281000, 0.007691}, {-0.843700, 0.007691, 134.300000}};
	static const float S = 4.000000;
	static const float b = 10.000000;
	static const float c = 0.400000;
	static const float CG[1][3] = {{0.000000, 0.000000, 0.000000}};
	static const float CP[1][3] = {{0.000000, 0.000000, 0.000000}};
	static const float thrustStatic = 8.000000;
	static const float thrustGain = 0.003400;
	static const float servoMap[5][5] = {{0.000000, 0.000000, 0.000000, 0.000000, 0.000000}, {0.000000, 0.000000, 0.000000, 0.000000, 0.000000}, {1.000000, 0.000000, 0.000000, 0.000000, 0.000000}, {0.000000, 1.000000, 0.000000, 0.000000, 0.000000}, {0.000000, 0.000000, 1.000000, 0.000000, 0.000000}};
	static const float servoMaxDeg[1][5] = {{0.000000, 0.000000, 25.000000, 15.000000, 15.000000}};
	static const float motorMap[2][2] = {{1.000000, 0.000000}, {0.000000, 1.000000}};
	static const float motorMax[1][2] = {{1.000000, 1.000000}};
};
